branches:
  - "master"
  - "+([0-9])?(.{+([0-9]),x}).x"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@covage/semantic-release-pyproject-plugin"

  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"

  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
        - "pyproject.toml"
      message: |-
        chore(release): ${nextRelease.version}

        ${nextRelease.notes}

  - "@semantic-release/github"
